---
title: "R Notebook"
output: html_notebook
---

```{r setup}
# setwd("C:/Users/levid/OneDrive/Desktop/GitHub/plane-fuel")

# Pacotes úteis
library(tidyverse)
library(lubridate)
library(e1071)
library(neuralnet)
library(caret)

# Defina o seed para reprodutibilidade
set.seed(123)

# Carregar bases
load("data_project_train.Rda")
load("data_project_test.Rda")
```

```{r}
# Conferir estrutura
summary(data_train)
```

## Feature Engineering

```{r}
df_train <- data_train %>%
  mutate(
    avg_speed = flown_distance_enr / (flight_duration / 60),        # NM/h
    fuel_per_nm = fuel_burn / flown_distance_enr,
    fuel_per_min = fuel_burn / flight_duration,
    total_ineff = kpi_inefficiency_dep + kpi_inefficiency_arr,
    flight_range = case_when(
      flown_distance_enr < 400 ~ "Curto",
      flown_distance_enr < 800 ~ "Médio",
      TRUE ~ "Longo"
    ),
    flight_range = factor(flight_range, levels = c('Curto', 'Médio', 'Longo')),
    dep_hour = hour(dep_time),
    dep_period = case_when(
      dep_hour >= 5 & dep_hour < 12 ~ "Manhã",
      dep_hour >= 12 & dep_hour < 18 ~ "Tarde",
      TRUE ~ "Noite"
    ),
    dep_period = factor(dep_period, levels = c("Manhã", "Tarde", "Noite"))
  )
```

```{r}
# Aplicar o mesmo processo à base de teste (sem fuel_burn)
df_test <- data_test %>%
  mutate(
    avg_speed = flown_distance_enr / (flight_duration / 60),
    total_ineff = kpi_inefficiency_dep + kpi_inefficiency_arr,
    flight_range = case_when(
      flown_distance_enr < 400 ~ "Curto",
      flown_distance_enr < 800 ~ "Médio",
      TRUE ~ "Longo"
    ),
    flight_range = factor(flight_range, levels = c('Curto', 'Médio', 'Longo')),
    dep_hour = hour(dep_time),
    dep_period = case_when(
      dep_hour >= 5 & dep_hour < 12 ~ "Manhã",
      dep_hour >= 12 & dep_hour < 18 ~ "Tarde",
      TRUE ~ "Noite"
    ),
    dep_period = factor(dep_period, levels = c("Manhã", "Tarde", "Noite"))
  )
```

## Análise Exploratória dos Dados

```{r}
hist(df_train$flight_duration, col='steelblue', breaks=20, xlab='Flight Duration (min)',main='Flight Duration Distribution')
```

```{r}
hist(df_train$dep_hour, col='steelblue', breaks = 24, xlab='Departure Hour',main='Departure Time Distribution')
```

```{r}
hist(df_train$flown_distance_enr, col='steelblue', breaks = 20, xlab='En Route Distance (nm)',main='Flown Distance En Route Distribution')
```

```{r}
# Distribuição do consumo
hist(df_train$fuel_burn, col='steelblue', breaks=40, xlab='Time flown',main='Fuel Burn Distribution')
```

```{r}
boxplot(fuel_burn ~ aircraft_type, df_train, col='steelblue')
```

```{r}
# PCA
x <- subset(data_train, select=c(8:12))

pca_out <- prcomp(x, scale=TRUE)

var_explained_pc <- pca_out$sdev^2
pve <- var_explained_pc/sum(var_explained_pc)

plot(cumsum(pve), xlab='PC', 
     ylab='Proportion of Variance Explained', type='b')
```

```{r}
data_train_pc <- data.frame(pca_out$x)
data_train_pc$fuel_burn <- data_train$fuel_burn %>% log1p() %>% 
                            scale() %>% as.numeric()

# Rodar o modelo
nn_model <- neuralnet(
  fuel_burn ~ PC1 + PC2 + PC3,
  data = data_train_pc,
  hidden = c(3),
  act.fct = 'tanh',
  linear.output = TRUE,
  threshold = 0.1
)

plot(nn_model)
```

```{r}
pred <- compute(nn_model, data_train_pc[, 1:3])$net.result
y_true <- data_train$fuel_burn
y_pred <- expm1(pred * sd(log1p(y_true)) + mean(log1p(y_true)))

RMSE <- sqrt(mean((y_pred - y_true)^2))
cat("RMSE =", RMSE)
```

```{r}
pred <- compute(nn_model, data_train_pc[, 1:3])$net.result
y_true <- data_train$fuel_burn
y_pred <- expm1(pred * sd(log1p(y_true)) + mean(log1p(y_true)))

RMSE <- mean(abs(y_pred - y_true)/y_true)
cat("RMSE =", RMSE)
```

```{r}
# Converte o resultado da previsão em vetor numérico
y_pred <- as.numeric(predict(nn_model, data_test))

# Substitui apenas os NAs por esses valores
data_test$fuel_burn <- y_pred
```
